### ISSUE TITLE
feature request: onboarding guide

### ISSUE THREAD

**Issue by trosel** [fiatjaf/branle#1]
I already lost my account because i didn’t back up my keys and i didn’t know the browser would erase local storage so quickly. 

oboarding should include:

1. advise to backup keys or mnemonic in a password manager 
2. basic info on where post data is stored
3. basic warnings on privacy (who can find you and how, data is all permanent, IP address exposure, best practice to separate identities since petnames can dox you)

**Comment by fiatjaf** [comment]
I think this is out of the scope for branle. We need better, generic Nostr guides elsewhere.
