### ISSUE TITLE
Feature Request: CTRL + Enter shortcut to add post/reply

### ISSUE THREAD

**Issue by 0xtrr** [fiatjaf/branle#14]
**Description**
On Twitter and Mastodon I'm able to write a post or a comment and then do CTRL + Enter to create the post. I think that would be a good feature on Branle as well.

I don't have much front end experience myself so I can't contribute anything myself.

**Comment by trosel** [comment]
counter point: Twitter and Mastodon let you delete posts while Nostr does not. 

Perhaps it is a good thing to make posting *slightly* more intentional.

**Comment by vinliao** [comment]
Check out https://github.com/fiatjaf/nostr/blob/master/nips/09.md. It will eventually support deletion (I think), but not "global delete" like Twitter or Mastodon. Twitter is centralized, it can do global delete; Nostr, SSB (secure scuttlebutt) are non-centralized, deletion is trickier.

**Comment by cameri** [comment]
fixed in #16, you may close this issue
