### ISSUE TITLE
Feature Request: Local data backup & restore

### ISSUE THREAD

**Issue by HamishMacEwan** [fiatjaf/branle#18]
Great that my identity can be initialised with the private key, but it comes back clean, without any of the earlier events or configuration of follows or relays.

If possible, a backup and restore (with some public/private key encryption) would be handy.

**Comment by fiatjaf** [comment]
It should come back with your follows and relays. Were you using nostr.com or branle.netlify.app? nostr.com is broken, do not use it.

**Comment by HamishMacEwan** [comment]
Using nostr.rocks and a server of my own.  With branle.netlify.app though, it did restore follows, relays and messages.
