### ISSUE TITLE
Not working in private browsing

### ISSUE THREAD

**Issue by emeceve** [fiatjaf/branle#5]
When using in a private browsing session the following error raises

```
Failed to open indexedDB, are you in private browsing mode? vendor.3d7f4559.js:26:111016
```

Browser:

Firefox Browser 94.0

**Comment by fiatjaf** [comment]
https://t.me/nostr_protocol/9429

If Firefox doesn't want to open indexedDB. There is nothing we can do except stop using browsers altogether.
