### ISSUE TITLE
Profile save button should be disable in public key mode

### ISSUE THREAD

**Issue by sondreb** [fiatjaf/branle#7]
When only the public key is provided, the "Save" button on the profile is enabled. Attempting to save, will result in error only logged to debug console. The "Publish" button is disable in public key mode, the "Save" button should probably too be disabled.

**Comment by monlovesmango** [comment]
looks like the 'Save' button on the profile is still enabled but pulls up a prompt to sign the changes with private key, which seems appropriate to me. do you think this is still an issue?

**Comment by fiatjaf** [comment]
No!
