### ISSUE TITLE
feature request: multi-account management

### ISSUE THREAD

**Issue by thrownness** [fiatjaf/branle#9]
Given that nip-005 will gossip your username all over the place, I think it will be necessary to allow people to maintain multiple accounts if they don't want social circles to overlap, or even if they just want a brand account and a personal account.

Multi-account management would be cool. Like if your device saves your keys for multiple accounts and you can switch between them quickly.

**Comment by fiatjaf** [comment]
It's cool but not worth the trouble. You can do it by having two browsers, two different profiles in the same browser, use branle hosted in two different domains etc.
